# Generated by Django 6.0.3 on 2026-05-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='content',
        ),
    ]
