# Generated by Django 6.0.3 on 2026-05-22 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession_app', '0001_initial'),
        ('notification_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='confession',
            field=models.ForeignKey(blank=True, db_column='confession_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='confession_app.confession'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('COMMENT', 'Comment'), ('REQUEST_CONNECT', 'Request Connect'), ('ROLE_APPROVAL', 'Role Approval'), ('REQUEST_CHANGE', 'Request Change')], default='COMMENT', max_length=30),
        ),
    ]
