# Generated by Django 6.0.3 on 2026-05-09 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('confession_app', '0001_initial'),
        ('position_app', '0005_position_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfessionPosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='confession_app.confession')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confessions', to='position_app.position')),
            ],
            options={
                'db_table': 'confession_positions',
                'unique_together': {('confession', 'position')},
            },
        ),
    ]
