# Generated by Django 6.0.3 on 2026-04-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
