# Generated by Django 6.0.3 on 2026-04-02 06:06

from django.db import migrations

def create_initial_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    
    # Using get_or_create to safely add them without duplication
    roles = ['STUDENT', 'STAFF', 'ADMIN']
    for role_name in roles:
        Role.objects.get_or_create(name=role_name)

def remove_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    
    roles = ['STUDENT', 'STAFF', 'ADMIN']
    Role.objects.filter(name__in=roles).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_table_alter_user_table'),
    ]

    operations = [
        migrations.RunPython(create_initial_roles, reverse_code=remove_roles)
    ]
