# Generated by Django 6.0.3 on 2026-04-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position_app', '0002_alter_position_name'),
        ('users', '0010_move_role_to_role_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='users', to='position_app.position'),
        ),
    ]
