# Generated by Django 6.0.3 on 2026-04-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='positions',
        ),
    ]
