# Generated by Django 6.0.3 on 2026-05-17 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
